# Generated by Django 4.2 on 2023-08-16 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_store_room_alter_category_name_alter_item_category_and_more'),
    ]

    operations = [
    ]
