# Generated by Django 4.2 on 2023-08-19 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_brand_item_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('size', models.CharField(max_length=20, null=True)),
                ('color', models.CharField(max_length=20, null=True)),
            ],
            options={
                'verbose_name_plural': 'Attribute',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='attribute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.attribute'),
        ),
    ]
