# Generated by Django 4.2 on 2023-08-21 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_attribute_item_attribute'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attribute',
            old_name='color',
            new_name='attribute_type',
        ),
        migrations.RenameField(
            model_name='attribute',
            old_name='name',
            new_name='model_name',
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='size',
        ),
        migrations.RemoveField(
            model_name='item',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='store',
            name='department',
        ),
        migrations.AddField(
            model_name='attribute',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.brand'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='generation',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='manufacture_year',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='expiry_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='imei',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='registered_date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='serial_no',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='warranty',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('hardware', 'hardware'), ('software', 'software')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
