# Generated by Django 4.2 on 2023-08-21 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_rename_color_attribute_attribute_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='manufacture_year',
            field=models.DateField(null=True),
        ),
    ]
