# Generated by Django 4.2 on 2023-08-21 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_item_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='generation',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
