# Generated by Django 4.2 on 2023-08-22 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_attribute_generation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-registered_date']},
        ),
    ]
