# Generated by Django 4.2 on 2023-08-25 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_alter_item_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='brand',
        ),
        migrations.AddField(
            model_name='item',
            name='model_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.attribute'),
        ),
    ]
