# Generated by Django 4.2 on 2023-08-29 09:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_item_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='expiry_date',
        ),
        migrations.AddField(
            model_name='item',
            name='last_updated',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='registered_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
