# Generated by Django 4.2 on 2023-08-29 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_remove_item_expiry_date_item_last_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='registered_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
