# Generated by Django 4.2 on 2023-09-02 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_item_receive_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='reorder_level',
            field=models.PositiveIntegerField(blank=True, default='0', null=True),
        ),
    ]
