# Generated by Django 4.2 on 2023-09-02 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_item_reorder_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='remarks',
            field=models.CharField(default='none', max_length=50, null=True),
        ),
    ]
