# Generated by Django 4.2 on 2024-06-24 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_alter_item_remarks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attribute',
            options={'ordering': ['-manufacture_year'], 'verbose_name_plural': 'Attribute'},
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['name'], 'verbose_name_plural': 'Brand'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-last_updated']},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ['name']},
        ),
    ]
