# Generated by Django 4.2 on 2023-08-22 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-issued_date']},
        ),
    ]
